spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
  profiles:
    active: dev
server:
  port: 8181
jwt_secret_key: ${JWT_SECRET}
access_expiration: ${ACCESS_TOKEN_EXPIRATION}
refresh_expiration: ${REFRESH_TOKEN_EXPIRATION}
